twitter-to-kafka-service:
  twitter-keywords:
    - Java
    - Microservices
    - Kafka
    - Elasticsearch
  welcome-message: Hello microservices!
  enable-mock-tweets: true
  mock-min-tweet-length: 5
  mock-max-tweet-length: 15
  mock-sleep-ms: 10000
  enable-v2-tweets: false
  twitter-v2-base-url: https://api.twitter.com/2/tweets/search/stream?tweet.fields=created_at&expansions=author_id
  twitter-v2-rules-base-url: https://api.twitter.com/2/tweets/search/stream/rules
  twitter-v2-bearer-token: AAAAAAAAAAAAAAAAAAAAAN1PhgEAAAAAd5%2BKBCtLY%2BQi76cRQtU6tPbgISs%3DgirLC77suwwKxMisnv9EKz2aAB3LvJr15sAsJIhDARIVu8HCjB